# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: First
    steps:
    - bash: echo build
  - job: Second
    steps:
    - bash: echo build
- stage: Dev
  dependsOn: Build
  jobs:
    - job: First
      steps:
      - bash: echo dev
- stage: QA
  dependsOn: Build
  jobs:
  - job: First
    steps:
     - bash: echo QA
- stage: staging
  dependsOn: QA
  jobs:
  - job: First
    steps:
     - bash: echo staging
- stage: Prod
  dependsOn:
  - Dev
  - QA
  - staging
  jobs:
  - job: First
    steps:
     - bash: echo Prod


