
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one scirpt line' 
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'aksterr'
    ensureBackend: true
    backendAzureRmResourceGroupLocation: 'terraform-backend-rg'
    backendAzureRmStorageAccountName: 'storageaccountdeva123'
    backendAzureRmContainerName: 'storageaccountdevacontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'